

{
  tokens=[number="regexp:\d+" string="regexp:\w+" IDENTIFIER="regexp:\w+"]
}
// a == x?b==y?i:j:k
// a==x?3*4:5==6
program ::= declaration* EOF;
declaration ::= varDecl
            | statement;
statement ::= exprStmt
    |printStmt
    |block;
    block ::= "{" declaration "}";
exprStmt ::= expression ";";
printStmt ::= "print" expression ";";

expression ::= comma;
assignment ::= IDENTIFIER "=" assignment
            |equality;
varDecl ::= "var" IDENTIFIER ( "=" expression)? ";";
ternary::= equality"?"ternary+":"ternary+;
comma ::= equality("," equality)*;
equality ::= comparison ( ("!=" | "==") comparison )*;
comparison ::= term ((">"|">="|"<"|"<=") term )*;
term ::= factor (("-"|"+") factor)*;
factor ::=unary(("/"|"*")unary)*;
unary ::=("!"|"-") unary
| primary;
primary ::= number|string|"true"|"false"|"nil"|"(" expression ")"|IDENTIFIER;


